spring.application.name=JazaCharge
spring.datasource.url=jdbc:h2:mem:jazacharge
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Africa's Talking
at.username=sandbox
at.api-key=${AT_API}

# Groq
groq.api-key=${GROQ_API}
groq.api-url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama3-8b-8192